### ISSUE TITLE
Screenshot appears to be modified by viewing

### ISSUE THREAD

**Issue by quozl** [sugarlabs/imageviewer-activity#31]
Reproducer: take a screenshot, show journal, view detail view for preview, click on the screenshot, observe ImageViewer start, click stop, show journal.

Observed result: (a) preview is changed; same image dimensions, but a border is added. (b) icon is changed.

Expected result: (a) preview is unchanged, (b) icon is unchanged.

_(a potentially complicated issue, as it goes to the heart of activity instantiation and resuming)_

**Comment by Saumya-Mishra9129** [comment]
@quozl I am not able to reproduce this, Maybe I didnt get what you said here,  can you explain what type of border is added to screenshot??

**Comment by quozl** [comment]
![Screenshot of _Journal__2](https://user-images.githubusercontent.com/2936481/87496269-91b25900-c696-11ea-813b-693c26097203.png)

![Screenshot of _Journal__1](https://user-images.githubusercontent.com/2936481/87496251-8c550e80-c696-11ea-81b3-bad932a22c9d.png)

![Screenshot of _Screenshot of _Home__](https://user-images.githubusercontent.com/2936481/87496281-9971fd80-c696-11ea-9475-88965407b40a.png)

![Screenshot of _Journal_](https://user-images.githubusercontent.com/2936481/87496303-a2fb6580-c696-11ea-99d1-cc551260bea7.png)

**Comment by quozl** [comment]
A white border.

**Comment by Saumya-Mishra9129** [comment]
I guess this , It is doing correct and what is expected to do. Journal object can be change by just looking at activity preview, because we are opening screenshot with image-viewer activity, it will replace old state which was a screenshot to image-viewer which is a new state. Hence preview icon and image both will change.
Better possible way if journal , in place of replacing old state with new one , will create a new state separately without effecting old state.

**Comment by quozl** [comment]
Why replace the image?  What is wrong with leaving the image unchanged?

**Comment by Saumya-Mishra9129** [comment]
> Why replace the image? What is wrong with leaving the image unchanged?

Because Journal works this way I guess. It always replace old state with new one. There is nothing wrong with leaving image unchaged, just journal is designed that way according to me.

**Comment by quozl** [comment]
I don't think Journal works that way.  Journal just does whatever the activity says to do.
